### ISSUE TITLE
"Create" button don't create a new website

### ISSUE THREAD

**Issue by Kobreros** [sebbouez/PageFabric#42] opened 2020-09-05 09:07 UTC
When I want to create a new website, the button does nothing. This is how it was at the beginning when I installed the software.
I have tried various settings and reinstalled. The video is attached.
![pagefabric-bug](https://user-images.githubusercontent.com/15179643/92301885-a9f07700-ef67-11ea-8aad-d04be5e17fc7.gif)

**Comment by sebbouez** [comment] 2020-09-05 09:12
Thank you for reporting it.
I'll investigate.

**Comment by sebbouez** [comment] 2020-09-05 09:24
The error is 
Указанный файл не может быть зашифрован. : 'W:\Work\PageFabric\Test\readme.page'

The specified file could not be encrypted. : 'W:\Work\PageFabric\Test\readme.page'

Are you trying to write to a specific disc that tries to encrypt all files?
Can you try with another location?

**Comment by Kobreros** [comment] 2020-09-05 09:33
Thanks for answering.

> Are you trying to write to a specific disc that tries to encrypt all files?
No, I don't have anything that can encrypt. Common disks and OS settings.
> Can you try with another location?
I have tried with other disks and folders, nothing changed.

**Comment by sebbouez** [comment] 2020-09-05 09:46
Well, the telemetry shows write access refused.

System.UnauthorizedAccessException | Access to the path 'G:\readme.page' is denied. 

I need to improve error handling to help users find out what happens.
Maybe you can have more information in Windows Event logs to know what process blocks access to the folder.

Thank you for your comments.

**Comment by sebbouez** [comment] 2020-09-05 10:04
I suspect that behavior may be caused by antivirus.
When I create the new site, I copy a set of default files to your specified location.
Maybe the antivirus doesn't accept to copy files from "program files" to another "less secured" folder.
I'll change the site creation process in next release. I hope it will fix it.

Thanks again for your participation.

**Comment by Kobreros** [comment] 2020-09-05 15:19
Just to notice, I have no antivirus, also the firewall is disabled and have tried with disabled Windows Defender Realtime.

**Comment by sebbouez** [comment] 2020-09-05 16:02
The problem seems to be with the copy operation that I do when you create a new site.
It may fail if Windows has encryption activated (EFS), see the post on MS Support -> Error 0x80071771
https://answers.microsoft.com/en-us/windows/forum/all/error-0x80071771/4d6140a5-8989-4ea4-bae1-88e4ed623812

It will be fixed in next release.

**Closed** 2020-09-10 18:00 UTC
Labels: bug, help wanted

**Comment by sebbouez** [comment] 2020-09-16 19:09
Hello,
The Beta 4 has been pushed to the Store on Tuesday. You should be able to get it now.
Can you try it?
Thank you.

**Comment by Kobreros** [comment] 2020-09-17 07:09
@sebbouez Yes, it works correct. Thanks.
